sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1212qwqw
  minio:
    endpoint: http://127.0.0.1:9000
    access-key-id: GkZPQgA2lFiaaiWifiSQ
    access-key-secret: UZtPi6HCh6EcQR6vGegZGuE27Bipq2Y2ufV6j6H7
    bucket-name: ctjnb

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wxe7144faa7eb05399
    secret: af9fbd1555ace1ca042913966e0a5e05